apiVersion: apps/v1 
kind: Deployment
metadata:
  name: clientes-deployment
  labels: 
     app: clientes
spec:
  selector:
    matchLabels:
      app: clientes
      version: v01
  template:
    metadata:
      labels:
        app: clientes
        version: v01
    spec:
      serviceAccountName: clientes-sa
      imagePullSecrets: 
        - name: docker-auth
      restartPolicy: Always
      containers:
      - name: clientes
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env: 
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"
